server.port=8080
spring.application.name=connectivity-forecast-api
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
api.service-name=internet-quality-api
api.models-file=classpath:data/models.json
api.predictions-file=classpath:data/predictions.csv
api.allowed-origins=*
api.timeline-default-limit=24
api.timeline-max-limit=100
